In [1]:
import os
import pandas as pd
from fractions import Fraction
from pandas_parallel_apply import DataFrameParallel, SeriesParallel
from typing import List, Tuple, Dict
from music21 import converter, meter, note, chord, instrument, stream
import warnings
warnings.filterwarnings('ignore')

In [2]:
DATA_PATH = os.path.join('data', 'MidiCaps')

In [3]:
df = pd.read_json('data/MidiCaps/train.json', lines=True)

In [9]:
df.sample(5)

,location,caption,genre,genre_prob,mood,mood_prob,key,time_signature,tempo,tempo_word,duration,duration_word,chord_summary,chord_summary_occurence,instrument_summary,instrument_numbers_sorted,all_chords,all_chords_timestamps,test_set
130214,lmd_full/a/a54ae781e4221b1a34a9134517c496c8.mid,This short electronic song in E major is a mel...,"[electronic, pop]","[0.5165000000000001, 0.19210000000000002]","[melodic, happy, dream, energetic, relaxing]","[0.11040000000000001, 0.0718, 0.0506, 0.0434, ...",E major,4/4,110.0,Moderato,89,Short song,"[Emaj7, A, B, E, A]",2,"[Electric Guitar, French Horn, Trumpet, Koto, ...","[26, 60, 60, 56, 107, 118, 117, 47]","[Emaj7, A, B, E, A, B, Emaj7, A, B, E, A, B, E...","[0.464399092, 8.54494331, 13.003174603, 17.461...",False
157994,lmd_full/6/6beed25bcfc615b5d6120426570adfc7.mid,A melodic and happy pop song featuring a piano...,"[pop, electronic]","[0.2142, 0.1635]","[melodic, happy, energetic, romantic, film]","[0.0949, 0.0876, 0.0687, 0.057300000000000004,...",C major,4/4,120.0,Allegro,128,Song,"[C, G7, C6, D7, G7]",2,[Piano],"[0, 0, 0]","[Ab, C, G, C, G7, C6, D7, G7, Bb7, Gaug, C, G7...","[0.9287981850000001, 1.486077097, 2.786394557,...",False
40327,lmd_full/0/0f029c74df96310ce70e663376c8eb52.mid,"This meditative electronic and ambient song, s...","[electronic, ambient]","[0.4968, 0.4299]","[meditative, relaxing, soundscape, space, dream]","[0.1772, 0.1563, 0.1124, 0.1121, 0.112]",C# major,4/4,104.0,Moderato,243,Song,"[F#, Ab, C#, F#, Ab]",14,"[Taiko Drum, String Ensemble, Synth Pad, Synth...","[116, 49, 89, 54, 52, 39, 39, 47, 28, 39, 117,...","[C#, F#, Ab, C#, F#, Ab, C#, F#, Ab, C#, F#, A...","[0.464399092, 31.393378683999998, 32.415056689...",False
133005,lmd_full/a/a88f757a7af3052d82177375e5215684.mid,"This uplifting pop song, infused with folk ele...","[pop, folk]","[0.37820000000000004, 0.2036]","[happy, christmas, melodic, motivational, corp...","[0.1715, 0.1389, 0.08360000000000001, 0.081200...",E major,4/4,125.0,Allegro,188,Song,"[E, A, B, E, A]",15,"[Accordion, Electric Piano, Piano, Acoustic Ba...","[21, 2, 0, 32, 128]","[E, A, B, E, A, E, A, B, E, A, B, E, A, B, E, ...","[5.94430839, 8.452063492, 11.052698412, 13.374...",False
40031,lmd_full/0/0f4651eba2f0f24c973fd098de523644.mid,This short electronic song radiates happiness ...,"[electronic, pop]","[0.4531, 0.2082]","[happy, melodic, game, corporate, christmas]","[0.2576, 0.22540000000000002, 0.1889, 0.0975, ...",F# major,4/4,152.0,Vivace,40,Short song,"[E, Ebm, Emaj7]",2,"[Piano, Synth Lead, Synth Brass, Fretless Bass...","[5, 1, 1, 81, 62, 35, 61, 128]","[F#6, E, Ebm, Emaj7, F#, Emaj7, Ebm, Edim, Ebm...","[0.464399092, 2.786394557, 3.993832199, 6.0371...",False

In [3]:
def filter_by_instrument_count(df, count):
    """
    Filter the dataframe by the number of instruments in the 'instrument_summary' column.

    Args:
        df (pd.DataFrame): The input dataframe.
        count (int): The desired number of instruments in the 'instrument_summary' list.

    Returns:
        pd.DataFrame: A filtered dataframe with rows where the number of instruments matches the given count.
    """
    return df[df['instrument_numbers_sorted'].apply(lambda x: len(x) <= count)]

def filter_by_genre(df, genre):
    """
    Filter the dataframe by the 'genre' column.

    Args:
        df (pd.DataFrame): The input dataframe.
        genre (str): The desired genre to filter by.

    Returns:
        pd.DataFrame: A filtered dataframe with rows where the genre matches the given genre.
    """
    return df[df['genre'].apply(lambda x: genre in x)]


def filter_by_time_signature(df):
    """
    Filter the dataframe by the 'time_signature' column.

    Args:
        df (pd.DataFrame): The input dataframe.
        time_signature (str): The desired time signature to filter by.

    Returns:
        pd.DataFrame: A filtered dataframe with rows where the time signature matches the given time signature.
    """
    return df[df['time_signature'].apply(lambda x: len(x) > 3)]

In [6]:
#df3 = filter_by_time_signature(df)

In [11]:
df2 = filter_by_instrument_count(df, 5)
# df2 = filter_by_genre(df2, 'jazz')

In [12]:
df.shape

(168385, 19)

In [13]:
df2.shape

(61667, 19)

In [13]:
df2.shape[0] / df.shape[0] * 100

24.873949579831933

In [4]:
print(df.iloc[0].to_dict())

{'location': 'lmd_full/1/1a0751ad20e2f82957410a7510a1b13e.mid', 'caption': 'A melodic electronic composition with classical influences, featuring a string ensemble, trumpet, brass section, synth strings, and drums. Set in F# minor with a 4/4 time signature, it moves at an Allegro tempo. The mood evokes a cinematic, spacious, and epic atmosphere while maintaining a sense of relaxation.', 'genre': ['electronic', 'classical'], 'genre_prob': [0.35960000000000003, 0.23670000000000002], 'mood': ['melodic', 'film', 'space', 'epic', 'relaxing'], 'mood_prob': [0.1228, 0.1114, 0.0917, 0.0828, 0.079], 'key': 'F# minor', 'time_signature': '4/4', 'tempo': 135.0, 'tempo_word': 'Allegro', 'duration': 59, 'duration_word': 'Short song', 'chord_summary': ['F#m', 'A/E', 'C#'], 'chord_summary_occurence': 2, 'instrument_summary': ['String Ensemble', 'Trumpet', 'Brass Section', 'Synth Strings', 'Drums'], 'instrument_numbers_sorted': [48, 56, 61, 50, 128, 35], 'all_chords': ['F#m', 'A/E', 'C#', 'F#m', 'C#', 'F#m', 'C#', 'D', 'C#', 'Bm', 'F#m', 'Bm', 'C#', 'D', 'Bm', 'C#', 'F#m', 'F#', 'C#', 'B', 'C#', 'F#', 'C#', 'F#', 'F#m', 'A/E', 'C#'], 'all_chords_timestamps': [0.464399092, 5.015510204, 5.758548752, 8.823582766, 10.866938775, 14.210612244, 16.161088435, 19.597641723, 21.362358276, 23.127074829, 24.984671201, 26.656507936, 28.514104308, 30.278820861, 31.950657596, 33.901133786, 35.480090702, 37.337687074, 39.288163265, 40.959999999, 42.817596371, 46.254149659, 48.111746031, 49.783582766, 51.548299319, 54.891972789, 55.542131519], 'test_set': False}

### TODO: 
* Filter all song with only 2 track
* Filter all song with only 1 or 2 instruments
* Align chords with relative timing by beats

In [4]:
def extract_midi_metadata(midi_file):
    """
    Extract metadata from a MIDI file, including the number of tracks, time signatures, tempo, and key signature.

    Args:
        midi_file (str): Path to the MIDI file.

    Returns:
        dict: A dictionary containing metadata such as number of tracks, time signatures, tempo, and key signature.
    """
    # Parse the MIDI file
    score = converter.parse(os.path.join(DATA_PATH, midi_file))
    #print(score.show('text'))
    # Count the number of parts (tracks)
    # num_tracks = len(score.parts)

    # instruments = []
    # for part in score.parts:
    #     inst = part.getElementsByClass('Instrument')
    #     #inst = part.getInstrument(returnDefault=True)
    #     instruments.append(str(inst[0]) if inst else "Unknown")
    
    instruments = score.recurse().getElementsByClass(instrument.Instrument)
    unique_instruments = set(instr.instrumentName or instr.bestName() for instr in instruments)

    # Extract time signatures
    time_signatures = [
        ts.ratioString for ts in score.recurse().getElementsByClass(meter.TimeSignature)
    ]
    # time_signatures = list(set(time_signatures))


    # Extract tempo
    # tempos = [
    #     t.number for t in score.recurse().getElementsByClass(tempo.MetronomeMark)
    # ]
    
    # Extract key signature
    #key_signature = score.analyze('key')
    
    
    # Return metadata as a dictionary
    return pd.Series({
        "num_tracks": len(unique_instruments),
        "time_signatures": list(set(time_signatures)),
        "instruments": list(unique_instruments)
    })

def extract_midi_metadata_to_df(df):
    """
    Apply the extract_midi_metadata function to a dataframe and create new columns for metadata.

    Args:
        df (pd.DataFrame): The input dataframe.
    Returns:
        pd.DataFrame: The dataframe with new metadata columns.
    """

    # Apply the extract_midi_metadata function to each MIDI file in the dataframe
    #metadata_df = df['location'].apply(lambda file: pd.Series(extract_midi_metadata(os.path.join(DATA_PATH, file))))
    #metadata_df = df['location'].apply(extract_midi_metadata)

    metadata_df = SeriesParallel(df['location'], n_cores=-1, pbar=True).apply(extract_midi_metadata)

    # print(type(metadata_df))
    # Concatenate the original dataframe with the metadata dataframe
    return pd.concat([df, metadata_df], axis=1)

In [23]:
df_test = extract_midi_metadata_to_df(df2)

Process-52: 100%|██████████| 1990/1990 [1:07:28<00:00,  2.03s/it]
Process-61: 100%|██████████| 1989/1989 [1:08:07<00:00,  2.06s/it]
Process-62: 100%|██████████| 1989/1989 [1:08:19<00:00,  2.06s/it]
Process-66: 100%|██████████| 1989/1989 [1:08:27<00:00,  2.07s/it]
Process-63: 100%|██████████| 1989/1989 [1:08:33<00:00,  2.07s/it]
Process-80: 100%|██████████| 1989/1989 [1:08:39<00:00,  2.07s/it]
Process-71: 100%|██████████| 1989/1989 [1:08:45<00:00,  2.07s/it]
Process-77: 100%|██████████| 1989/1989 [1:08:47<00:00,  2.08s/it]
Process-69: 100%|██████████| 1989/1989 [1:08:48<00:00,  2.08s/it]
Process-64: 100%|██████████| 1989/1989 [1:08:50<00:00,  2.08s/it]
Process-81: 100%|██████████| 1989/1989 [1:08:51<00:00,  2.08s/it]
Process-74: 100%|██████████| 1989/1989 [1:08:54<00:00,  2.08s/it]
Process-79: 100%|██████████| 1989/1989 [1:09:16<00:00,  2.09s/it]
Process-70: 100%|██████████| 1989/1989 [1:09:38<00:00,  2.10s/it]
Process-68: 100%|██████████| 1989/1989 [1:09:39<00:00,  2.10s/it]
Process-51: 100%|██████████| 1990/1990 [1:09:47<00:00,  2.10s/it]
Process-76: 100%|██████████| 1989/1989 [1:09:48<00:00,  2.11s/it]
Process-56: 100%|██████████| 1990/1990 [1:10:10<00:00,  2.12s/it]
Process-59: 100%|██████████| 1989/1989 [1:10:15<00:00,  2.12s/it]
Process-54: 100%|██████████| 1990/1990 [1:10:23<00:00,  2.12s/it]
Process-58: 100%|██████████| 1990/1990 [1:10:29<00:00,  2.13s/it]
Process-57: 100%|██████████| 1990/1990 [1:10:30<00:00,  2.13s/it]
Process-65: 100%|██████████| 1989/1989 [1:10:31<00:00,  2.13s/it]
Process-60: 100%|██████████| 1989/1989 [1:10:32<00:00,  2.13s/it]
Process-72: 100%|██████████| 1989/1989 [1:10:34<00:00,  2.13s/it]
Process-75: 100%|██████████| 1989/1989 [1:10:44<00:00,  2.13s/it]
Process-67: 100%|██████████| 1989/1989 [1:11:00<00:00,  2.14s/it]
Process-55: 100%|██████████| 1990/1990 [1:11:01<00:00,  2.14s/it]
Process-53: 100%|██████████| 1990/1990 [1:11:03<00:00,  2.14s/it]
Process-78: 100%|██████████| 1989/1989 [1:11:27<00:00,  2.16s/it]
Process-73: 100%|██████████| 1989/1989 [1:31:15<00:00,  2.75s/it]

In [ ]:
#df_test.to_json('data/MidiCaps/train2.json', lines=True, orient='records')

In [21]:
df_test.head()

,location,caption,genre,genre_prob,mood,mood_prob,key,time_signature,tempo,tempo_word,...,chord_summary,chord_summary_occurence,instrument_summary,instrument_numbers_sorted,all_chords,all_chords_timestamps,test_set,num_tracks,time_signatures,instruments
1,lmd_full/1/164fcc530a285bdb8066c6aa8616c95b.mid,A cheerful and melodic Christmas song that ble...,"[classical, pop]","[0.19140000000000001, 0.1836]","[christmas, happy, melodic, corporate, adventure]","[0.1763, 0.1688, 0.1643, 0.1282, 0.07200000000...",Eb major,2/4,124.0,Allegro,...,"[Eb, Bb7, Eb, Fm]",5,"[Tango Accordion, Clarinet, Acoustic Guitar, D...","[23, 71, 25, 128, 32]","[Bb7, Eb, Bb7, Eb, Fm, Eb, Bb7, Eb, Bb7, Eb, F...","[0.464399092, 6.780226757, 9.84526077, 13.7462...",False,5,[2/4],"[Acoustic Guitar, Acoustic Bass, Accordion, Cl..."
2,lmd_full/1/16b9a230fb007c0009feee532c3c4686.mid,This energetic electronic and classical compos...,"[electronic, classical]","[0.21480000000000002, 0.1806]","[energetic, film, melodic, happy, dark]","[0.10790000000000001, 0.1062, 0.09580000000000...",C major,4/4,120.0,Moderate tempo,...,"[C, G, C, C7]",2,[],[],"[C, G, C, C7, Dm, C, G, C, C7, Bbmaj7, C, G7, ...","[0.464399092, 4.086712018, 7.430385487, 8.9164...",False,1,[4/4],[None]
3,lmd_full/1/17655598958db48a34cd882f81402568.mid,A short electronic ambient song featuring a pi...,"[electronic, ambient]","[0.30310000000000004, 0.2369]","[film, energetic, melodic, epic, dark]","[0.11620000000000001, 0.11080000000000001, 0.1...",E major,4/4,170.0,Presto,...,"[B, Emaj7, C#m7, B7, A]",5,[Piano],[0],"[B, Emaj7, C#m7, B7, A, B, Emaj7, C#m7, B7, A,...","[0.464399092, 1.30031746, 2.972154195, 3.71519...",False,1,[4/4],[Piano]
6,lmd_full/1/180b3a492c1c1a46d005e762d62b9aa4.mid,A cheerful pop song with a touch of electronic...,"[pop, electronic]","[0.4238, 0.2548]","[happy, love, melodic, christmas, motivational]","[0.1521, 0.09870000000000001, 0.0935, 0.0737, ...",D major,4/4,96.0,Moderate tempo,...,"[A7, D, Em7, A7, D]",4,"[Piano, Drums]","[0, 0, 0, 128, 0]","[D, A7, D, Em, A, D, Em7, A7, D, Em7, A7, D, G...","[0.464399092, 7.616145124, 9.938140589, 12.353...",False,5,[4/4],"[guitar, strings, bass, Piano, Percussion]"
7,lmd_full/1/12697568a5c06fe9fd0bae8b715f57f0.mid,A short classical and electronic piece that ev...,"[classical, electronic]","[0.2291, 0.219]","[film, melodic, relaxing, epic, emotional]","[0.1395, 0.0699, 0.0694, 0.0689, 0.0658]",A major,3/4,104.0,Moderate tempo,...,"[A, E7, A, Bm6, F#m]",1,"[Piano, Violin, String Ensemble]","[0, 40, 0, 48, 48]","[A, E7, A, Bm6, F#m, B7/D#, Emaj7, A, E, A]","[6.59446712, 9.19510204, 11.052698412, 16.8112...",False,6,[3/4],"[Violin, A.PIANO 1, VIOLIN, STRINGS, Piano, St..."

In [5]:
df3 = pd.read_json(os.path.join(DATA_PATH, 'train2.json'), lines=True)

In [6]:
df3.head()

,location,caption,genre,genre_prob,mood,mood_prob,key,time_signature,tempo,tempo_word,...,chord_summary,chord_summary_occurence,instrument_summary,instrument_numbers_sorted,all_chords,all_chords_timestamps,test_set,num_tracks,time_signatures,instruments
0,lmd_full/1/164fcc530a285bdb8066c6aa8616c95b.mid,A cheerful and melodic Christmas song that ble...,"[classical, pop]","[0.19140000000000001, 0.1836]","[christmas, happy, melodic, corporate, adventure]","[0.1763, 0.1688, 0.1643, 0.1282, 0.07200000000...",Eb major,2/4,124.0,Allegro,...,"[Eb, Bb7, Eb, Fm]",5,"[Tango Accordion, Clarinet, Acoustic Guitar, D...","[23, 71, 25, 128, 32]","[Bb7, Eb, Bb7, Eb, Fm, Eb, Bb7, Eb, Bb7, Eb, F...","[0.464399092, 6.780226757, 9.84526077, 13.7462...",False,5,[2/4],"[Acoustic Guitar, Acoustic Bass, Accordion, Cl..."
1,lmd_full/1/16b9a230fb007c0009feee532c3c4686.mid,This energetic electronic and classical compos...,"[electronic, classical]","[0.21480000000000002, 0.1806]","[energetic, film, melodic, happy, dark]","[0.10790000000000001, 0.1062, 0.09580000000000...",C major,4/4,120.0,Moderate tempo,...,"[C, G, C, C7]",2,[],[],"[C, G, C, C7, Dm, C, G, C, C7, Bbmaj7, C, G7, ...","[0.464399092, 4.086712018, 7.430385487, 8.9164...",False,1,[4/4],[None]
2,lmd_full/1/17655598958db48a34cd882f81402568.mid,A short electronic ambient song featuring a pi...,"[electronic, ambient]","[0.30310000000000004, 0.2369]","[film, energetic, melodic, epic, dark]","[0.11620000000000001, 0.11080000000000001, 0.1...",E major,4/4,170.0,Presto,...,"[B, Emaj7, C#m7, B7, A]",5,[Piano],[0],"[B, Emaj7, C#m7, B7, A, B, Emaj7, C#m7, B7, A,...","[0.464399092, 1.30031746, 2.972154195, 3.71519...",False,1,[4/4],[Piano]
3,lmd_full/1/180b3a492c1c1a46d005e762d62b9aa4.mid,A cheerful pop song with a touch of electronic...,"[pop, electronic]","[0.4238, 0.2548]","[happy, love, melodic, christmas, motivational]","[0.1521, 0.09870000000000001, 0.0935, 0.0737, ...",D major,4/4,96.0,Moderate tempo,...,"[A7, D, Em7, A7, D]",4,"[Piano, Drums]","[0, 0, 0, 128, 0]","[D, A7, D, Em, A, D, Em7, A7, D, Em7, A7, D, G...","[0.464399092, 7.616145124, 9.938140589, 12.353...",False,5,[4/4],"[guitar, strings, bass, Piano, Percussion]"
4,lmd_full/1/12697568a5c06fe9fd0bae8b715f57f0.mid,A short classical and electronic piece that ev...,"[classical, electronic]","[0.2291, 0.219]","[film, melodic, relaxing, epic, emotional]","[0.1395, 0.0699, 0.0694, 0.0689, 0.0658]",A major,3/4,104.0,Moderate tempo,...,"[A, E7, A, Bm6, F#m]",1,"[Piano, Violin, String Ensemble]","[0, 40, 0, 48, 48]","[A, E7, A, Bm6, F#m, B7/D#, Emaj7, A, E, A]","[6.59446712, 9.19510204, 11.052698412, 16.8112...",False,6,[3/4],"[Violin, A.PIANO 1, VIOLIN, STRINGS, Piano, St..."

In [ ]:
# df3.to_json('data/MidiCaps/train_metadata.json', lines=True, orient='records')

In [ ]:


def count_initial_silence_notes(path, silence_threshold_beats=16):
    """
    Count how many notes/rests are silent at the very beginning of a MIDI file.
    
    Args:
        midi_path (str): path to the midi file
        silence_threshold_beats (float): stop counting after this many beats of silence

    Returns:
        int: number of silent/rest notes at the beginning
    """
    file_path = os.path.join(DATA_PATH, path)
    score = converter.parse(file_path)
    flat = score.flatten().notesAndRests.stream()
    ts = flat.getTimeSignatures()[0]

    total_duration = flat.highestTime  # Total duration in quarter lengths
    # measure_length = ts.barDuration.quarterLength  # e.g., 4.0 for 4/4

    beats_per_measure = ts.numerator
    beat_unit = ts.beatDuration.quarterLength  # e.g., 1 for quarter note, 0.5 for eighth

    measure_length = beats_per_measure * beat_unit

    estimated_measures = int(total_duration / measure_length)  # round up
    # measures_count = 0
    # if len(score.parts) > 0:
    #     part = score.parts[0]
    #     measures = part.recurse().getElementsByClass(stream.Measure)
    #     measures_count = len(measures)

    silent_count = 0
    accumulated_beats = 0.0

    for el in flat:
        if isinstance(el, note.Rest):
            silent_count += 1
            accumulated_beats += el.quarterLength
        elif isinstance(el, note.Note) and el.volume.velocity == 0:
            silent_count += 1
            accumulated_beats += el.quarterLength
        elif isinstance(el, chord.Chord) and all(p.volume.velocity == 0 for p in el.notes):
            silent_count += 1
            accumulated_beats += el.quarterLength
        else:
            # First sounding note/chord appears
            break

        if accumulated_beats > silence_threshold_beats:
            break

    return pd.Series({
        "num_silent_notes": silent_count,
        "num_silent_beats": accumulated_beats,
        "num_measures": estimated_measures
    })


def count_slient_notes_to_df(df):
    """
    Apply the extract_midi_metadata function to a dataframe and create new columns for metadata.

    Args:
        df (pd.DataFrame): The input dataframe.
    Returns:
        pd.DataFrame: The dataframe with new metadata columns.
    """

    # Apply the extract_midi_metadata function to each MIDI file in the dataframe
    #metadata_df = df['location'].apply(lambda file: pd.Series(extract_midi_metadata(os.path.join(DATA_PATH, file))))
    #n_silence = df['location'].apply(count_initial_silence_notes)

    df_filtered = SeriesParallel(df['location'], n_cores=-1, pbar=True).apply(count_initial_silence_notes)

    # n_silence_series = pd.Series(n_silence, name="num_init_silence")
    # print(type(n_silence))
    # print(type(metadata_df))
    # Concatenate the original dataframe with the metadata dataframe
    return pd.concat([df, df_filtered], axis=1)

In [8]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61667 entries, 0 to 61666
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   location                   61667 non-null  object
 1   caption                    61667 non-null  object
 2   genre                      61667 non-null  object
 3   genre_prob                 61667 non-null  object
 4   mood                       61667 non-null  object
 5   mood_prob                  61667 non-null  object
 6   key                        61524 non-null  object
 7   time_signature             61667 non-null  object
 8   tempo                      60594 non-null  float64
 9   tempo_word                 60594 non-null  object
 10  duration                   61667 non-null  int64
 11  duration_word              61667 non-null  object
 12  chord_summary              61401 non-null  object
 13  chord_summary_occurence    61667 non-null  int64
 14  instrument_summary         61667 non-null  object
 15  instrument_numbers_sorted  61667 non-null  object
 16  all_chords                 61667 non-null  object
 17  all_chords_timestamps      61667 non-null  object
 18  test_set                   61667 non-null  bool
 19  num_tracks                 61667 non-null  int64
 20  time_signatures            61667 non-null  object
 21  instruments                61667 non-null  object
dtypes: bool(1), float64(1), int64(3), object(17)
memory usage: 9.9+ MB

In [8]:
df3 = df3.dropna()

In [9]:
df4 = df3[df3['instrument_summary'].apply(lambda x: len(x) > 0)]

In [14]:
df_test = df4[df4['location'] == 'lmd_full/1/17655598958db48a34cd882f81402568.mid']

In [17]:
df_test['location'].apply(count_initial_silence_notes)

   num_silent_notes  num_silent_beats  counted_measures  est_measures
2               0.0               0.0              71.0          71.0

In [10]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 51247 entries, 0 to 61666
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   location                   51247 non-null  object
 1   caption                    51247 non-null  object
 2   genre                      51247 non-null  object
 3   genre_prob                 51247 non-null  object
 4   mood                       51247 non-null  object
 5   mood_prob                  51247 non-null  object
 6   key                        51247 non-null  object
 7   time_signature             51247 non-null  object
 8   tempo                      51247 non-null  float64
 9   tempo_word                 51247 non-null  object
 10  duration                   51247 non-null  int64
 11  duration_word              51247 non-null  object
 12  chord_summary              51247 non-null  object
 13  chord_summary_occurence    51247 non-null  int64
 14  instrument_summary         51247 non-null  object
 15  instrument_numbers_sorted  51247 non-null  object
 16  all_chords                 51247 non-null  object
 17  all_chords_timestamps      51247 non-null  object
 18  test_set                   51247 non-null  bool
 19  num_tracks                 51247 non-null  int64
 20  time_signatures            51247 non-null  object
 21  instruments                51247 non-null  object
dtypes: bool(1), float64(1), int64(3), object(17)
memory usage: 8.7+ MB

In [11]:
df5 = count_slient_notes_to_df(df4)

Process-0:   0%|          | 0/1654 [00:00<?, ?it/s]


Process-2:   0%|          | 0/1654 [00:00<?, ?it/s]




Process-3:   0%|          | 0/1654 [00:00<?, ?it/s]





































Process-11:   0%|          | 0/1653 [00:00<?, ?it/s]























































Process-13:   0%|          | 0/1653 [00:00<?, ?it/s]









































































































































































































































Process-0:   0%|          | 2/1654 [00:02<27:54,  1.01s/it]




































































































































Process-16:   0%|          | 4/1653 [00:02<12:17,  2.24it/s]

















































































































































































































Process-0:   0%|          | 6/1654 [00:04<15:08,  1.81it/s]
























































































Process-5:   0%|          | 8/1653 [00:04<20:18,  1.35it/s]



































Process-8:   0%|          | 4/1653 [00:04<27:03,  1.02it/s]
















Process-2:   1%|          | 9/1654 [00:04<11:24,  2.40it/s]


























































































Process-0:   0%|          | 8/1654 [00:05<18:17,  1.50it/s]






































































































Process-0:   1%|          | 10/1654 [00:05<13:11,  2.08it/s]


























































Process-13:   0%|          | 7/1653 [00:06<20:19,  1.35it/s]



























































































































Process-0:   1%|          | 12/1654 [00:07<15:49,  1.73it/s]



















































































































Process-0:   1%|          | 13/1654 [00:07<15:06,  1.81it/s]




















































Process-0:   1%|          | 14/1654 [00:08<12:30,  2.19it/s]



























































Process-12:   1%|          | 9/1653 [00:08<22:01,  1.24it/s]



























































































 ... (more hidden) ...






Process-8:   0%|          | 8/1653 [00:08<29:49,  1.09s/it]
























































































































































Process-0:   1%|          | 15/1654 [00:09<21:18,  1.28it/s]


























































































































































































































Process-0:   1%|          | 16/1654 [00:11<28:04,  1.03s/it]




















































































































Process-0:   1%|          | 20/1654 [00:12<11:14,  2.42it/s]

































































































































































































































































Process-0:   1%|▏         | 21/1654 [00:13<18:43,  1.45it/s]


















Process-0:   1%|▏         | 22/1654 [00:14<15:38,  1.74it/s]






















































































































































































































Process-17:   1%|▏         | 24/1653 [00:15<08:35,  3.16it/s]










































































Process-0:   2%|▏         | 25/1654 [00:15<13:31,  2.01it/s]






























































































































Process-11:   2%|▏         | 26/1653 [00:16<19:38,  1.38it/s]

























Process-8:   1%|          | 16/1653 [00:16<22:37,  1.21it/s]

















































































































































































































Process-0:   2%|▏         | 29/1654 [00:17<11:45,  2.30it/s]








































































































































































































































































Process-5:   2%|▏         | 36/1653 [00:19<17:18,  1.56it/s]




















































































Process-16:   1%|▏         | 22/1653 [00:19<18:49,  1.44it/s]









Process-9:   1%|▏         | 24/1653 [00:19<26:53,  1.01it/s]








































































































































































































































































































































































































































Process-0:   2%|▏         | 31/1654 [00:21<26:44,  1.01it/s]

















































































































































































































Process-17:   2%|▏         | 35/1653 [00:22<16:36,  1.62it/s]



















































































































































































































Process-0:   2%|▏         | 32/1654 [00:23<34:51,  1.29s/it]














Process-0:   2%|▏         | 33/1654 [00:24<28:15,  1.05s/it]




































































Process-17:   2%|▏         | 40/1653 [00:24<13:30,  1.99it/s]





































































Process-9:   2%|▏         | 26/1653 [00:24<46:55,  1.73s/it]










































































































































































































































































































Process-0:   2%|▏         | 37/1654 [00:26<21:15,  1.27it/s]
















































































































Process-16:   2%|▏         | 39/1653 [00:27<13:09,  2.04it/s]














































































































Process-0:   2%|▏         | 38/1654 [00:28<25:33,  1.05it/s]
















































































































































Process-2:   2%|▏         | 39/1654 [00:28<24:39,  1.09it/s]




































































Process-2:   2%|▏         | 40/1654 [00:29<19:47,  1.36it/s]
















































































































Process-0:   2%|▏         | 39/1654 [00:29<30:59,  1.15s/it]




























































































































Process-18:   2%|▏         | 36/1653 [00:30<09:31,  2.83it/s]
































































































































































Process-17:   3%|▎         | 46/1653 [00:31<19:53,  1.35it/s]
















































Process-0:   2%|▏         | 40/1654 [00:31<35:05,  1.30s/it]


































































































































































































































































































































Process-0:   3%|▎         | 43/1654 [00:34<26:27,  1.01it/s]







































































































































































































































































Process-0:   3%|▎         | 44/1654 [00:35<30:47,  1.15s/it]




































































































































































































































































Process-14:   3%|▎         | 47/1653 [00:37<36:15,  1.35s/it]










































































































































Process-0:   3%|▎         | 47/1654 [00:38<26:30,  1.01it/s]


























































Process-0:   3%|▎         | 48/1654 [00:38<21:16,  1.26it/s]































































































































































































Process-0:   3%|▎         | 51/1654 [00:39<16:32,  1.61it/s]









Process-0:   3%|▎         | 53/1654 [00:39<10:35,  2.52it/s]


































































Process-12:   3%|▎         | 49/1653 [00:40<15:12,  1.76it/s]






























































































































































































































Process-0:   3%|▎         | 54/1654 [00:41<19:30,  1.37it/s]]



























Process-11:   4%|▎         | 59/1653 [00:41<13:24,  1.98it/s]


















Process-0:   4%|▎         | 58/1654 [00:42<09:20,  2.85it/s]
























































































































































































































































Process-3:   4%|▍         | 70/1654 [00:43<12:55,  2.04it/s]


Process-4:   4%|▍         | 69/1653 [00:43<14:36,  1.81it/s]
































































Process-0:   4%|▎         | 60/1654 [00:43<13:15,  2.00it/s]









Process-0:   4%|▍         | 64/1654 [00:44<07:31,  3.52it/s]



































































































































































































































































Process-0:   4%|▍         | 65/1654 [00:45<13:59,  1.89it/s]







Process-0:   4%|▍         | 68/1654 [00:45<08:01,  3.29it/s]





























































































































































































































































Process-17:   4%|▍         | 69/1653 [00:47<19:36,  1.35it/s]

Process-1:   4%|▍         | 65/1654 [00:47<20:56,  1.26it/s]


































































































Process-0:   4%|▍         | 70/1654 [00:48<14:13,  1.86it/s]
























































































































































































































































































































































































































































Process-10:   4%|▍         | 67/1653 [00:50<12:15,  2.16it/s]














Process-5:   5%|▌         | 83/1653 [00:50<16:32,  1.58it/s]












Process-14:   4%|▍         | 64/1653 [00:50<24:45,  1.07it/s]


















Process-5:   5%|▌         | 84/1653 [00:50<12:54,  2.03it/s]






































































































































Process-0:   4%|▍         | 72/1654 [00:51<22:54,  1.15it/s]







Process-0:   5%|▍         | 75/1654 [00:51<14:42,  1.79it/s]










































Process-0:   5%|▍         | 77/1654 [00:51<11:09,  2.36it/s]














































































































































































Process-12:   4%|▍         | 63/1653 [00:52<24:47,  1.07it/s]

















































































































































































































Process-1:   5%|▍         | 80/1654 [00:53<09:04,  2.89it/s]

























Process-0:   5%|▍         | 80/1654 [00:54<16:25,  1.60it/s]


































Process-0:   5%|▍         | 82/1654 [00:54<12:51,  2.04it/s]
















Process-17:   5%|▌         | 85/1653 [00:54<10:32,  2.48it/s]





























































































































































































 ... (more hidden) ...



































































































































Process-0:   5%|▌         | 83/1654 [00:56<19:37,  1.33it/s]































































Process-0:   5%|▌         | 85/1654 [00:56<13:31,  1.93it/s]






















































































































































































































































Process-0:   5%|▌         | 86/1654 [00:58<20:07,  1.30it/s]



































































Process-0:   5%|▌         | 87/1654 [00:58<17:08,  1.52it/s]










































































Process-10:   5%|▍         | 75/1653 [00:59<28:58,  1.10s/it]




























































































































































Process-11:   5%|▍         | 80/1653 [00:59<30:35,  1.17s/it]


Process-0:   5%|▌         | 88/1654 [00:59<22:12,  1.18it/s]








































Process-0:   5%|▌         | 89/1654 [01:00<18:50,  1.38it/s]










Process-0:   5%|▌         | 90/1654 [01:00<14:57,  1.74it/s]






















































































































































































































































































Process-0:   6%|▌         | 92/1654 [01:01<16:55,  1.54it/s]



























Process-1:   6%|▌         | 95/1654 [01:02<13:07,  1.98it/s]

























Process-0:   6%|▌         | 93/1654 [01:02<14:32,  1.79it/s]












































Process-4:   6%|▋         | 105/1653 [01:02<08:58,  2.88it/s]














































































 ... (more hidden) ...[A




















































































































Process-0:   6%|▌         | 94/1654 [01:03<20:48,  1.25it/s]


















































































































Process-0:   6%|▌         | 95/1654 [01:04<18:22,  1.41it/s]







































































































































































































































































































































Process-0:   6%|▌         | 96/1654 [01:05<25:27,  1.02it/s]

































































































































































































































































































Process-1:   7%|▋         | 111/1654 [01:07<07:10,  3.59it/s]






Process-0:   6%|▌         | 98/1654 [01:07<25:55,  1.00it/s]









Process-0:   6%|▌         | 100/1654 [01:07<14:49,  1.75it/s]




























































Process-17:   6%|▌         | 102/1653 [01:07<27:34,  1.07s/it]






































































































































































































































Process-0:   6%|▌         | 101/1654 [01:09<24:00,  1.08it/s]













































































































































































































 ... (more hidden) ...















































































































































Process-9:   6%|▌         | 94/1653 [01:11<29:15,  1.13s/it]





































Process-0:   6%|▌         | 103/1654 [01:11<24:46,  1.04it/s]


















































































































































































































































































































































Process-11:   7%|▋         | 111/1653 [01:13<10:24,  2.47it/s]












































Process-13:   7%|▋         | 122/1653 [01:13<23:02,  1.11it/s]





































































































































Process-0:   6%|▋         | 104/1654 [01:14<36:24,  1.41s/it]
























































































































Process-0:   6%|▋         | 105/1654 [01:15<30:39,  1.19s/it]


































Process-0:   6%|▋         | 107/1654 [01:15<18:41,  1.38it/s]



























































































































































































































































































































Process-0:   7%|▋         | 109/1654 [01:17<20:42,  1.24it/s]






























Process-0:   7%|▋         | 111/1654 [01:17<15:41,  1.64it/s]

















































































Process-9:   6%|▌         | 100/1653 [01:18<24:12,  1.07it/s]


































































In [18]:
df5.to_json(os.path.join(DATA_PATH, 'train3.json'), lines=True, orient="records")

In [19]:
df5.head(10)

,location,caption,genre,genre_prob,mood,mood_prob,key,time_signature,tempo,tempo_word,...,instrument_numbers_sorted,all_chords,all_chords_timestamps,test_set,num_tracks,time_signatures,instruments,num_silent_notes,num_silent_beats,num_measures
0,lmd_full/1/164fcc530a285bdb8066c6aa8616c95b.mid,A cheerful and melodic Christmas song that ble...,"[classical, pop]","[0.19140000000000001, 0.1836]","[christmas, happy, melodic, corporate, adventure]","[0.1763, 0.1688, 0.1643, 0.1282, 0.07200000000...",Eb major,2/4,124.0,Allegro,...,"[23, 71, 25, 128, 32]","[Bb7, Eb, Bb7, Eb, Fm, Eb, Bb7, Eb, Bb7, Eb, F...","[0.464399092, 6.780226757, 9.84526077, 13.7462...",False,5,[2/4],"[Acoustic Guitar, Acoustic Bass, Accordion, Cl...",9.0,18.0,87.0
2,lmd_full/1/17655598958db48a34cd882f81402568.mid,A short electronic ambient song featuring a pi...,"[electronic, ambient]","[0.30310000000000004, 0.2369]","[film, energetic, melodic, epic, dark]","[0.11620000000000001, 0.11080000000000001, 0.1...",E major,4/4,170.0,Presto,...,[0],"[B, Emaj7, C#m7, B7, A, B, Emaj7, C#m7, B7, A,...","[0.464399092, 1.30031746, 2.972154195, 3.71519...",False,1,[4/4],[Piano],0.0,0.0,71.0
3,lmd_full/1/180b3a492c1c1a46d005e762d62b9aa4.mid,A cheerful pop song with a touch of electronic...,"[pop, electronic]","[0.4238, 0.2548]","[happy, love, melodic, christmas, motivational]","[0.1521, 0.09870000000000001, 0.0935, 0.0737, ...",D major,4/4,96.0,Moderate tempo,...,"[0, 0, 0, 128, 0]","[D, A7, D, Em, A, D, Em7, A7, D, Em7, A7, D, G...","[0.464399092, 7.616145124, 9.938140589, 12.353...",False,5,[4/4],"[guitar, strings, bass, Piano, Percussion]",5.0,20.0,94.0
4,lmd_full/1/12697568a5c06fe9fd0bae8b715f57f0.mid,A short classical and electronic piece that ev...,"[classical, electronic]","[0.2291, 0.219]","[film, melodic, relaxing, epic, emotional]","[0.1395, 0.0699, 0.0694, 0.0689, 0.0658]",A major,3/4,104.0,Moderate tempo,...,"[0, 40, 0, 48, 48]","[A, E7, A, Bm6, F#m, B7/D#, Emaj7, A, E, A]","[6.59446712, 9.19510204, 11.052698412, 16.8112...",False,6,[3/4],"[Violin, A.PIANO 1, VIOLIN, STRINGS, Piano, St...",7.0,17.0,12.0
5,lmd_full/1/1b5441111ee9cd5242590a1714c7c9ce.mid,"A slow-paced classical piece, likely part of a...","[classical, soundtrack]","[0.5925, 0.2124]","[film, dark, relaxing, epic, romantic]","[0.22610000000000002, 0.07540000000000001, 0.0...",C major,6/8,80.0,Slow,...,"[40, 42, 40, 41]","[C, F, C, G, Dm, C, Am, G, Bdim, C, Bdim, C, F...","[0.464399092, 4.643990929, 5.387029478, 6.8731...",True,11,[6/8],"[Trumpet, Violin, Viola, Soprano, Bass, Alto, ...",8.0,12.0,41.0
6,lmd_full/1/1f94f64f72af98fd92f206293b281f6f.mid,A classical piece that could be part of a film...,"[classical, soundtrack]","[0.6144000000000001, 0.225]","[film, relaxing, emotional, documentary, drama]","[0.16640000000000002, 0.1048, 0.0655, 0.0621, ...",C# major,4/4,74.0,Andante,...,[74],"[C#, Fm, Ab, C#, Fm, Bbm, C, Bbm, B, Bb, Ab, F...","[0.464399092, 1.764716553, 9.752380952, 11.609...",False,1,[4/4],[Recorder],0.0,0.0,28.0
7,lmd_full/1/1c72504009e57e0ce9a98dd129d3805d.mid,A dark and melodic electronic soundtrack featu...,"[electronic, soundtrack]","[0.3506, 0.18150000000000002]","[slow, dark, melodic, film, epic]","[0.1409, 0.1385, 0.10310000000000001, 0.0781, ...",C major,3/4,150.0,Vivace,...,"[39, 104, 0, 128]","[G, A, E, G, A, E, G, A, E, G, A, E, C, G, Em,...","[0.464399092, 2.972154195, 3.808072562, 6.8731...",False,9,[3/4],"[cymbal, electric guitar, Electric Bass, Sitar...",4.0,6.0,160.0
8,lmd_full/1/112139e8b17be9cae1bd14df56e52f14.mid,A short fragment of energetic electronic and c...,"[electronic, classical]","[0.32370000000000004, 0.30610000000000004]","[energetic, film, dark, epic, action]","[0.1081, 0.1009, 0.0961, 0.0916, 0.0896]",F major,4/4,136.0,Allegro,...,"[0, 0]","[A, F/A]","[0.464399092, 1.671836734]",False,2,[4/4],"[intro bass (MIDI), Piano]",0.0,0.0,8.0
9,lmd_full/1/1ae5e3999b6beaf5ca7e3680b87e7181.mid,A joyful and melodic electronic rock song with...,"[electronic, rock]","[0.3085, 0.2931]","[happy, melodic, game, corporate, positive]","[0.21280000000000002, 0.12150000000000001, 0.1...",C major,4/4,170.0,Very fast,...,"[26, 7, 128, 35, 10]","[C, F6, C, F, G, C, F6, C, F, G, Dm7, C/G, F, ...","[0.464399092, 4.086712018, 5.665668934, 6.9659...",False,6,[4/4],"[Glockenspiel, Clavichord, Fretless Bs., Elect...",1.0,4.0,89.0
10,lmd_full/1/1a20c7ecf60469366d1121ea48fd3f6e.mid,A short classical piece with electronic elemen...,"[classical, electronic]","[0.22660000000000002, 0.21530000000000002]","[dark, film, melodic, relaxing, emotional]","[0.0932, 0.0925, 0.0881, 0.0776, 0.0687]",C major,4/4,108.0,Moderato,...,"[0, 0]","[C, G7/B, Am7, Dm, C, Em7, C]","[0.464399092, 24.42739229, 26.470748299, 38.82...",False,3,[4/4],"[Piano (hi), Piano, Piano (lo)]",0.0,0.0,32.0

Incorrect files:
* lmd_full/1/17fecee2cf25f4d3d2eecb3e670a2df9.mid
* lmd_full/1/14bdef979c3d2e9816dff833d9a4be29.mid

In [6]:
def count_total_unique_instruments(midi_path):
    score = converter.parse(midi_path)
    all_instrs = score.recurse().getElementsByClass(instrument.Instrument)
    unique_instr_names = set(instr.instrumentName or instr.bestName() for instr in all_instrs)
    print(len(score.parts))
    return  len(all_instrs), len(unique_instr_names), unique_instr_names

In [7]:
midi_file = 'data/MidiCaps/lmd_full/1/17655598958db48a34cd882f81402568.mid'
#metadata = extract_midi_metadata(midi_file)
ins_counts, unique_ins, ins_name = count_total_unique_instruments(midi_file)
print(ins_counts, unique_ins)
print(ins_name)
# print(metadata)

1
1 1
{'Piano'}